name: neural_style_transfer
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - freetype=2.10.2
  - icu=64.2
  - intel-openmp=2020.1
  - jpeg=9d
  - kiwisolver=1.2.0
  - libclang=9.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ninja=1.10.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.2.0
  - pip=20.2.2
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.6.9
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.6.0
  - qt=5.12.5
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.7.0
  - tornado=6.0.4
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
